// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisManagement.Web.Infrastructure.Persistance;

#nullable disable

namespace TennisManagement.Web.Migrations
{
    [DbContext(typeof(TennisManagementContext))]
    [Migration("20260930133006_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TennisManagement.Web.Models.Country.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Congo (Brazzaville)"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61,
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Holy See"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 78,
                            Name = "India"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 129,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Palestine State"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 150,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 162,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 163,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 164,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 186,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 187,
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Matches.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CourtType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("FirstPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("MatchFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatchKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ScoreResult")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SecondPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirstPlayerId");

                    b.HasIndex("SecondPlayerId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("VenueId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Roster.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Coach");
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Roster.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Birthplace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 36,
                            Birthplace = "Belgrade, Serbia",
                            CountryId = 154,
                            FirstName = "Novak",
                            Height = "6'2\"/(188cm)",
                            LastName = "Djokovic",
                            Weight = "170 lbs/(77kg)"
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            Birthplace = "El Palmar, Murcia, Spain",
                            CountryId = 165,
                            FirstName = "Carlos",
                            Height = "6'0\"/(183cm)",
                            LastName = "Alcaraz",
                            Weight = "163 lbs/(74kg)"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            Birthplace = "Innichen, Italy",
                            CountryId = 84,
                            FirstName = "Jannik",
                            Height = "6'3\"/(191cm)",
                            LastName = "Sinner",
                            Weight = "168 lbs/(76kg)"
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            Birthplace = "Moscow, Russia",
                            CountryId = 114,
                            FirstName = "Daniil",
                            Height = "6'6\"/(198cm)",
                            LastName = "Medvedev",
                            Weight = "183 lbs/(83kg)"
                        },
                        new
                        {
                            Id = 5,
                            Age = 26,
                            Birthplace = "Hamburg, Germany",
                            CountryId = 65,
                            FirstName = "Alexander",
                            Height = "6'6\"/(198cm)",
                            LastName = "Zverev",
                            Weight = "198 lbs/(90kg)"
                        },
                        new
                        {
                            Id = 6,
                            Age = 35,
                            Birthplace = "Haskovo, Bulgaria",
                            CountryId = 26,
                            FirstName = "Grigor",
                            Height = "6'3\"/(191cm)",
                            LastName = "Dimitrov",
                            Weight = "178 lbs/(80kg)"
                        },
                        new
                        {
                            Id = 7,
                            Age = 28,
                            Birthplace = "Athens, Greece",
                            CountryId = 67,
                            FirstName = "Stefanos",
                            Height = "6'4\"/(193cm)",
                            LastName = "Tsitsipas",
                            Weight = "198 lbs/(90kg)"
                        },
                        new
                        {
                            Id = 8,
                            Age = 27,
                            Birthplace = "Oslo, Norway",
                            CountryId = 130,
                            FirstName = "Casper",
                            Height = "6'0\"/(183cm)",
                            LastName = "Ruud",
                            Weight = "178 lbs/(81kg)"
                        },
                        new
                        {
                            Id = 9,
                            Age = 23,
                            Birthplace = "Gentofte, Denmark",
                            CountryId = 47,
                            FirstName = "Holger",
                            Height = "6'2\"/(188cm)",
                            LastName = "Rune",
                            Weight = "169 lbs/(77kg)"
                        },
                        new
                        {
                            Id = 10,
                            Age = 28,
                            Birthplace = "Rancho Santa Fe, California, USA",
                            CountryId = 187,
                            FirstName = "Taylor",
                            Height = "6'5\"/(196cm)",
                            LastName = "Fritz",
                            Weight = "185 lbs/(84kg)"
                        },
                        new
                        {
                            Id = 11,
                            Age = 27,
                            Birthplace = "Sydney, Australia",
                            CountryId = 9,
                            FirstName = "Alex",
                            Height = "6'0\"/(183cm)",
                            LastName = "de Minaur",
                            Weight = "152 lbs/(69kg)"
                        },
                        new
                        {
                            Id = 12,
                            Age = 28,
                            Birthplace = "Moscow, Russia",
                            CountryId = 144,
                            FirstName = "Andrey",
                            Height = "6'2\"/(188cm)",
                            LastName = "Rublev",
                            Weight = "165 lbs/(75kg)"
                        },
                        new
                        {
                            Id = 13,
                            Age = 29,
                            Birthplace = "Wroclaw, Poland",
                            CountryId = 140,
                            FirstName = "Hubert",
                            Height = "6'5\"/(196cm)",
                            LastName = "Hurkacz",
                            Weight = "179 lbs/(81kg)"
                        },
                        new
                        {
                            Id = 14,
                            Age = 23,
                            Birthplace = "Atlanta, Georgia, USA",
                            CountryId = 187,
                            FirstName = "Ben",
                            Height = "6'4\"/(193cm)",
                            LastName = "Shelton",
                            Weight = "195 lbs/(88kg)"
                        },
                        new
                        {
                            Id = 15,
                            Age = 28,
                            Birthplace = "Hyattsville, Maryland, USA",
                            CountryId = 187,
                            FirstName = "Frances",
                            Height = "6'2\"/(188cm)",
                            LastName = "Tiafoe",
                            Weight = "190 lbs/(86kg)"
                        },
                        new
                        {
                            Id = 16,
                            Age = 28,
                            Birthplace = "Metz, France",
                            CountryId = 61,
                            FirstName = "Ugo",
                            Height = "6'2\"/(188cm)",
                            LastName = "Humbert",
                            Weight = "161 lbs/(73kg)"
                        },
                        new
                        {
                            Id = 17,
                            Age = 26,
                            Birthplace = "Bradenton, Florida, USA",
                            CountryId = 187,
                            FirstName = "Sebastian",
                            Height = "6'5\"/(196cm)",
                            LastName = "Korda",
                            Weight = "175 lbs/(79kg)"
                        },
                        new
                        {
                            Id = 18,
                            Age = 24,
                            Birthplace = "Carrara, Italy",
                            CountryId = 84,
                            FirstName = "Lorenzo",
                            Height = "6'1\"/(185cm)",
                            LastName = "Musetti",
                            Weight = "165 lbs/(75kg)"
                        },
                        new
                        {
                            Id = 19,
                            Age = 24,
                            Birthplace = "Sutton, London, United Kingdom",
                            CountryId = 186,
                            FirstName = "Jack",
                            Height = "6'4\"/(193cm)",
                            LastName = "Draper",
                            Weight = "187 lbs/(85kg)"
                        },
                        new
                        {
                            Id = 20,
                            Age = 26,
                            Birthplace = "Montreal, Canada",
                            CountryId = 32,
                            FirstName = "Felix",
                            Height = "6'4\"/(193cm)",
                            LastName = "Auger-Aliassime",
                            Weight = "194 lbs/(88kg)"
                        },
                        new
                        {
                            Id = 21,
                            Age = 25,
                            Birthplace = "Mar del Plata, Argentina",
                            CountryId = 7,
                            FirstName = "Francisco",
                            Height = "5'10\"/(178cm)",
                            LastName = "Comesana",
                            Weight = "165 lbs/(75kg)"
                        },
                        new
                        {
                            Id = 22,
                            Age = 31,
                            Birthplace = "Johannesburg, South Africa",
                            CountryId = 186,
                            FirstName = "Cameron",
                            Height = "6'2\"/(188cm)",
                            LastName = "Norrie",
                            Weight = "180 lbs/(82kg)"
                        },
                        new
                        {
                            Id = 23,
                            Age = 41,
                            Birthplace = "Lausanne, Switzerland",
                            CountryId = 170,
                            FirstName = "Stan",
                            Height = "6'0\"/(183cm)",
                            LastName = "Wawrinka",
                            Weight = "179 lbs/(81kg)"
                        },
                        new
                        {
                            Id = 24,
                            Age = 40,
                            Birthplace = "Paris, France",
                            CountryId = 61,
                            FirstName = "Gaël",
                            Height = "6'4\"/(193cm)",
                            LastName = "Monfils",
                            Weight = "187 lbs/(85kg)"
                        },
                        new
                        {
                            Id = 25,
                            Age = 30,
                            Birthplace = "Rome, Italy",
                            CountryId = 84,
                            FirstName = "Matteo",
                            Height = "6'5\"/(196cm)",
                            LastName = "Berrettini",
                            Weight = "210 lbs/(95kg)"
                        },
                        new
                        {
                            Id = 26,
                            Age = 30,
                            Birthplace = "Moscow, Russia",
                            CountryId = 144,
                            FirstName = "Karen",
                            Height = "6'6\"/(198cm)",
                            LastName = "Khachanov",
                            Weight = "192 lbs/(87kg)"
                        },
                        new
                        {
                            Id = 27,
                            Age = 25,
                            Birthplace = "Buenos Aires, Argentina",
                            CountryId = 7,
                            FirstName = "Sebastian",
                            Height = "5'7\"/(170cm)",
                            LastName = "Baez",
                            Weight = "154 lbs/(70kg)"
                        },
                        new
                        {
                            Id = 28,
                            Age = 28,
                            Birthplace = "Buenos Aires, Argentina",
                            CountryId = 7,
                            FirstName = "Francisco",
                            Height = "6'1\"/(185cm)",
                            LastName = "Cerundolo",
                            Weight = "172 lbs/(78kg)"
                        },
                        new
                        {
                            Id = 29,
                            Age = 29,
                            Birthplace = "Toronto, Canada",
                            CountryId = 35,
                            FirstName = "Alejandro",
                            Height = "6'2\"/(188cm)",
                            LastName = "Tabilo",
                            Weight = "165 lbs/(75kg)"
                        },
                        new
                        {
                            Id = 30,
                            Age = 30,
                            Birthplace = "Santiago, Chile",
                            CountryId = 35,
                            FirstName = "Nicolas",
                            Height = "6'7\"/(201cm)",
                            LastName = "Jarry",
                            Weight = "198 lbs/(90kg)"
                        },
                        new
                        {
                            Id = 31,
                            Age = 27,
                            Birthplace = "La Plata, Argentina",
                            CountryId = 7,
                            FirstName = "Tomas Martin",
                            Height = "6'5\"/(196cm)",
                            LastName = "Etcheverry",
                            Weight = "181 lbs/(82kg)"
                        },
                        new
                        {
                            Id = 32,
                            Age = 22,
                            Birthplace = "Courcouronnes, France",
                            CountryId = 61,
                            FirstName = "Arthur",
                            Height = "6'1\"/(185cm)",
                            LastName = "Fils",
                            Weight = "183 lbs/(83kg)"
                        },
                        new
                        {
                            Id = 33,
                            Age = 38,
                            Birthplace = "Soisy-sous-Montmorency, France",
                            CountryId = 61,
                            FirstName = "Adrian",
                            Height = "6'0\"/(183cm)",
                            LastName = "Mannarino",
                            Weight = "174 lbs/(79kg)"
                        },
                        new
                        {
                            Id = 34,
                            Age = 36,
                            Birthplace = "Warstein, Germany",
                            CountryId = 65,
                            FirstName = "Jan-Lennard",
                            Height = "6'4\"/(193cm)",
                            LastName = "Struff",
                            Weight = "203 lbs/(92kg)"
                        },
                        new
                        {
                            Id = 35,
                            Age = 32,
                            Birthplace = "Sydney, Australia",
                            CountryId = 9,
                            FirstName = "Jordan",
                            Height = "6'0\"/(183cm)",
                            LastName = "Thompson",
                            Weight = "181 lbs/(82kg)"
                        },
                        new
                        {
                            Id = 36,
                            Age = 29,
                            Birthplace = "Maia, Portugal",
                            CountryId = 141,
                            FirstName = "Nuno",
                            Height = "6'1\"/(185cm)",
                            LastName = "Borges",
                            Weight = "165 lbs/(75kg)"
                        },
                        new
                        {
                            Id = 37,
                            Age = 26,
                            Birthplace = "Budapest, Hungary",
                            CountryId = 76,
                            FirstName = "Fabian",
                            Height = "6'4\"/(193cm)",
                            LastName = "Marozsan",
                            Weight = "165 lbs/(75kg)"
                        },
                        new
                        {
                            Id = 38,
                            Age = 27,
                            Birthplace = "Sydney, Australia",
                            CountryId = 9,
                            FirstName = "Alexei",
                            Height = "6'5\"/(196cm)",
                            LastName = "Popyrin",
                            Weight = "172 lbs/(78kg)"
                        },
                        new
                        {
                            Id = 39,
                            Age = 25,
                            Birthplace = "Sanremo, Italy",
                            CountryId = 84,
                            FirstName = "Matteo",
                            Height = "5'11\"/(180cm)",
                            LastName = "Arnaldi",
                            Weight = "157 lbs/(71kg)"
                        },
                        new
                        {
                            Id = 40,
                            Age = 23,
                            Birthplace = "Lyon, France",
                            CountryId = 61,
                            FirstName = "Giovanni",
                            Height = "6'8\"/(203cm)",
                            LastName = "Mpetshi Perricard",
                            Weight = "216 lbs/(98kg)"
                        });
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Tournaments.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tournament");
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Tournaments.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Matches.Match", b =>
                {
                    b.HasOne("TennisManagement.Web.Models.Roster.Player", "FirstPlayer")
                        .WithMany()
                        .HasForeignKey("FirstPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisManagement.Web.Models.Roster.Player", "SecondPlayer")
                        .WithMany()
                        .HasForeignKey("SecondPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisManagement.Web.Models.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisManagement.Web.Models.Tournaments.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisManagement.Web.Models.Roster.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FirstPlayer");

                    b.Navigation("SecondPlayer");

                    b.Navigation("Tournament");

                    b.Navigation("Venue");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Roster.Coach", b =>
                {
                    b.HasOne("TennisManagement.Web.Models.Roster.Player", "Player")
                        .WithMany("Coaches")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Roster.Player", b =>
                {
                    b.HasOne("TennisManagement.Web.Models.Country.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TennisManagement.Web.Models.Roster.Player", b =>
                {
                    b.Navigation("Coaches");
                });
#pragma warning restore 612, 618
        }
    }
}
